apiVersion: apps/v1
kind: Deployment

metadata:
  name: redis
  namespace: wanderlust

  labels:
    app: redis
    tier: cache

spec:
  replicas: {{ .Values.redis.replicaCount }}

  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis
        tier: cache

    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.redis.containerPort }}

          resources:
          {{- toYaml .Values.redis.resources | nindent 10 }}

          livenessProbe:
            tcpSocket:
              port: {{ .Values.redis.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 10

          readinessProbe:
            tcpSocket:
              port: {{ .Values.redis.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10