apiVersion: v2

name: wanderlust

description: Helm chart for deploying the Wanderlust application stack on Kubernetes.

type: application

version: 0.1.18

appVersion: "18"

keywords:
  - wanderlust
  - devops
  - kubernetes
  - helm
  - nodejs

home: https://github.com/pushpendra-singh1176/wanderlust

sources:
  - https://github.com/pushpendra-singh1176/wanderlust
  - https://github.com/pushpendra-singh1176/wanderlust-infrastructure

maintainers:
  - name: Pushpendra Singh

icon: https://helm.sh/img/helm.svg