rules:
  - host: wanderlust.com

    http:
      paths:
        - path: /
          pathType: Prefix

          backend:
            service:
              name: frontend
              port:
                number: 80

        - path: /api
          pathType: Prefix

          backend:
            service:
              name: backend
              port:
                number: 5000

    
  