apiVersion: apps/v1
kind: Deployment  

metadata:
  name: "{{ .Release.Name }}-frontend"
  namespace: {{ .Release.Namespace }}

  labels:
    app: "{{ .Release.Name }}-frontend"
    tier: frontend

spec:
  replicas: {{ .Values.frontend.replicaCount }}

  selector:
    matchLabels:
      app: "{{ .Release.Name }}-frontend"

  strategy:
    type: RollingUpdate

    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-frontend"
        tier: frontend

    spec:
      containers:
        - name: "{{ .Release.Name }}-frontend"

          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"

          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
              protocol: TCP

          resources:
          {{- toYaml .Values.frontend.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.containerPort }}
            initialDelaySeconds: {{ .Values.frontend.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.livenessProbe.periodSeconds }}

          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.containerPort }}
            initialDelaySeconds: {{ .Values.frontend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.readinessProbe.periodSeconds }}