apiVersion: apps/v1
kind: Deployment

metadata:
  name: "{{ .Release.Name }}-backend"
  namespace: wanderlust

  labels:
    app: wanderlust-backend
    tier: backend

spec:
  replicas: {{ .Values.backend.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  selector:
    matchLabels:
      app: wanderlust-backend

  template:

    metadata:
      labels:
        app: wanderlust-backend
        tier: backend

    spec:
      restartPolicy: Always
      containers:
      - name: wanderlust-backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ .Values.backend.configMapName }}
        - secretRef:
            name: {{ .Values.backend.secretName }}
        ports:
        - containerPort: {{ .Values.backend.containerPort }}
          protocol: TCP

        resources:
          requests:
            memory: {{ .Values.backend.resources.requests.memory }}
            cpu: {{ .Values.backend.resources.requests.cpu }}
          limits:
            memory: {{ .Values.backend.resources.limits.memory }}
            cpu: {{ .Values.backend.resources.limits.cpu }}
        livenessProbe:
          httpGet:
            path: {{ .Values.backend.livenessProbe.path }}
            port: {{ .Values.backend.containerPort }}
          initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.backend.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.backend.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.backend.livenessProbe.failureThreshold }}
        readinessProbe:
          httpGet:
            path: {{ .Values.backend.livenessProbe.path }}
            port: {{ .Values.backend.containerPort }}
          initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.backend.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.backend.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.backend.readinessProbe.failureThreshold }}