apiVersion: v1
kind: ConfigMap

metadata:
  name: "{{ .Release.Name }}-backend-config"
  namespace: {{ .Release.Namespace }}

  labels:
    app: "{{ .Release.Name }}-backend"
    tier: backend

data:
  NODE_ENV: {{ .Values.backend.nodeEnv }}

  PORT: {{ .Values.backend.config.port }}

  FRONTEND_URL: {{ .Values.backend.config.frontendUrl }}

  MONGO_HOST: {{ .Values.backend.config.mongoHost }}

  MONGO_PORT: {{ .Values.backend.config.mongoPort }}

  REDIS_HOST: {{ .Values.backend.config.redisHost }}

  REDIS_PORT: {{ .Values.backend.config.redisPort }}

  DATABASE_NAME: {{ .Values.backend.config.databaseName }}