apiVersion: v1
kind: Secret

metadata:
  name: "{{ .Release.Name }}-backend-secret"
  namespace: {{ .Release.Namespace }}

  labels:
    app: "{{ .Release.Name }}-backend"
    tier: backend

type: Opaque

stringData:
  JWT_SECRET: {{ .Values.backend.secret.jwtSecret }}
  MONGODB_URI: {{ .Values.backend.secret.mongodbUri }}

  REDIS_URL: {{ .Values.backend.secret.redisUrl }}

  GOOGLE_CLIENT_ID: {{ .Values.backend.secret.googleClientId }}

  GOOGLE_CLIENT_SECRET: {{ .Values.backend.secret.googleClientSecret }}