apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: wanderlust

  labels:
    app: wanderlust-frontend
    tier: frontend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: wanderlust-frontend

  strategy:
    type: RollingUpdate

    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: wanderlust-frontend
        tier: frontend

    spec:
      containers:
        - name: frontend

          image: xerox2/wanderlust-frontend:9

          imagePullPolicy: Always

          ports:
            - containerPort: 5173

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "300m"
              memory: "256Mi"

          livenessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 20
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 10
            periodSeconds: 5