apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.mongodb.service.name }}
  namespace: {{ .Release.Namespace }}

  labels:
    app: mongodb
    tier: database

spec:
  clusterIP: {{ .Values.mongodb.service.clusterIP }}

  selector:
    app: mongodb

  ports:
    - name: mongodb
      port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.containerPort }}

      