apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: {{ .Release.Name }}-mongodb
  namespace: {{ .Release.Namespace }}

  labels:
    app: mongodb
    tier: database

spec:
  serviceName: mongodb-service

  replicas: {{ .Values.mongodb.replicaCount }}

  selector:
    matchLabels:
      app: mongodb

  template:
    metadata:
      labels:
        app: mongodb
        tier: database

    spec:
      containers:
        - name: mongodb
          image: {{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}
          imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.mongodb.containerPort }}

          env:
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.mongodb.database | quote }}

          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db

          resources:
          {{- toYaml .Values.mongodb.resources | nindent 12 }}

  volumeClaimTemplates:
    - metadata:
        name: mongodb-storage

      spec:
        accessModes:
          - {{ .Values.mongodb.persistence.accessMode }}

        resources:
          requests:
            storage: {{ .Values.mongodb.persistence.size }}